import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport:
    "height=device-height,width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0,user-scalable=no, target-densitydpi=device-dpi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative w-full flex min-h-screen items-center justify-between">
          <SideBar />
          <section className="relative flex flex-col ml-24 px-8 pt-8 w-full bg-primary">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
